manifest = "0180dd782b145dab8b42a8d1b08ab16191a9b52d6fc7a7dc8483c944a1dfe851"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.50.0" ]
revision = "0af936e42c3db7c0f8a63e21265a645b70abb9cb"
