manifest = "a260a7e8ff68b3195f3e44b2d0956c7ce849a9f5f62ef3d3df0a60d7139e05a6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.2" ]
revision = "0368528c3989e727bd67b791b31fcf415b6311ac"
