manifest = "8fa118ce7e3f9b436a2f616d7d6f769b2d0de4640792ae70a481fcb2c39c48a2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.36.0" ]
revision = "137ef6f9d5cbf9e3b9b61ff052c564cb7bb3cd00"
