manifest = "a27e786e7bd5e56a8e47b24723e52d3f1e9c4a8dd2195f49ebd25dddb02a154e"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.64.0" ]
revision = "9cbe0f1be39466ec9b76b35b81295959fd417de0"
